<?php namespace Buuug7\User\Components;

use Cms\Classes\ComponentBase;
use RainLab\User\Facades\Auth;

class Account extends ComponentBase
{
    public function componentDetails()
    {
        return [
            'name' => 'Account Component',
            'description' => 'No description provided yet...'
        ];
    }

    public function defineProperties()
    {
        return [];
    }


    public function init()
    {
        $user = Auth::getUser();
        if ($user) {
            $component = $this->addComponent(
                'NetSTI\Uploader\Components\ImageUploader',
                'imageUploader',
                [
                    'modelClass' => 'RainLab\User\Models\User',
                    'modelKeyColumn' => 'avatar',
                    'deferredBinding' => false,
                ]
            );

            $component->bindModel('avatar', $user);
        }
    }

    public function onRun()
    {
        parent::onRun(); // TODO: Change the autogenerated stub
    }


}
